name: Deploy Laravel to EC2

on:
  push:
    branches:
      - master  # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH Key
        env:
          KEY: ${{ secrets.KEY }}
          HOST: ${{ secrets.HOST }}  # Replace with your EC2 instance's public DNS
        run: |
          echo "$KEY" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Execute Commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}        # Replace with your EC2 instance's public DNS
          username: ec2-user                # Change if you use a different user (e.g., ubuntu)
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/html/laravelapp
            git config --global --add safe.directory /var/www/html/laravelapp
            git add .
            git commit -m "serversidechanges" || echo "No changes to commit"
            git pull origin main
            php artisan migrate --force
            php artisan serve --host=0.0.0.0 --port=8000
