name: Deploy Laravel on EC2
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        key: ${{ secrets.KEY }} # Ensure KEY is your base64 encoded key
        port: 22 # Adjust the port if necessary
        script: |
          cd /var/www/html/laravelapp
          git config --global --add safe.directory /var/www/html/laravelapp
          git add .
          git commit -m "serverside changes" || echo "No changes to commit"
          git pull origin main
          php artisan migrate
          php artisan serve --host=0.0.0.0 --port=8000
