name: Laravel CI/CD

on:
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer Dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader || {
            echo "Composer installation failed. Checking composer diagnostics:";
            composer diagnose;
            exit 1;
          }
        env:
          COMPOSER_PROCESS_TIMEOUT: 2000

      - name: Verify Composer Installation
        run: |
          if [ ! -d "vendor" ]; then
            echo "Error: Vendor directory missing. Composer dependencies were not installed."
            exit 1
          fi

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
